version: '3.8'

services:
  openai_bot:
    build:
      context: fastapi/
      dockerfile: tgbot/Dockerfile
    container_name: tgbot_app
    restart: on-failure
    command: ["python", "tgbot/aiogram_bot.py"]

  fastapi:
    build: fastapi
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    command: [ "uvicorn", "web:app", "--host", "0.0.0.0", "--port", "8000" ]

  db:
    image: postgres
    restart: always
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: neurobot
      PGDATA: /data/postgres

    volumes:
      - ./postgres:/data/postgres

  nginx:
    image: nginx:latest

    build:
      context: nginx/
      dockerfile: nginx/Dockerfile

    volumes:
      - /nginx/nginx.conf:/etc/nginx/nginx.conf
      - /nginx/conf.d:/etc/nginx/conf.d

    depends_on:
      - fastapi
    ports:
      - 80:80
    restart: unless-stopped

